import Base
using Distributions
using Logging


# They can move in any of four directions.
@enum Direction NoDirection Up Left Down Right
const DirectionDelta = Dict(
    Up => CartesianIndex(-1, 0),
    Left => CartesianIndex(0, -1),
    Down => CartesianIndex(1, 0),
    Right => CartesianIndex(0, 1),
    );
const DirectionOpposite = Dict(
    Up => Down, Down => Up, Left => Right, Right => Left
)

@enum Health NoHealth Healthy Sick Dead
@enum HealthEvent NoEvent Infect Recover Die

const PlaceKey = Tuple
# The last element is an int here but can be a direction.
const ClockKey = Tuple
export run

@tracked_struct Square begin
    occupant::Int
    resistance::Float64
end


@tracked_struct Agent begin
    health::Health
    loc::CartesianIndex{2}
    birthtime::Float64
end

const BoardIndices = CartesianIndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}

# There are agents located on a 2D board.
# The state is a checkerboard. Each plaquette in the checkerboard
# is 0 or contains an individual identified by an integer.
# An individual has a health state.
mutable struct BoardState <: PhysicalState
    board::TrackedVector{Square}
    agent::TrackedVector{Agent}
    # The tracked_vector is 1D but the board is 2D so we have to save conversion.
    board_dim::BoardIndices

    function BoardState(board::AbstractArray)
        linboard = TrackedVector{Square}(undef, length(board))
        for (i, val) in enumerate(board)
            linboard[i] = Square(val, 1.0)
        end
        location = findall(x -> x != 0, board)
        agent = TrackedVector{Agent}(undef, length(location))
        for (i, loc) in enumerate(location)
            agent[i] = Agent(Healthy, loc, 0.0)
        end
        new(linboard, agent, CartesianIndices(board))
    end
end


function isconsistent(physical::BoardState)
    # Check that the board is consistent with the agents.
    seen_agents = Set{Int}()
    for square in eachindex(physical.board)
        if physical.board[square].occupant != 0
            agent_idx = physical.board[square].occupant
            if agent_idx in seen_agents
                @error "Inconsistent board: square $square has occupant $agent_idx but it was already seen"
                return false
            end
            push!(seen_agents, agent_idx)
            agent_loc = physical.agent[agent_idx].loc
            if agent_loc != physical.board_dim[square]
                @error "Inconsistent board: square $square has occupant $agent_idx at location $agent_loc but should be at $(physical.board_dim[square])"
                return false
            end
        end
    end
    @assert seen_agents == Set(1:length(physical.agent))
    return true
end


function move_agent(physical, agentidx, destination)
    old_loc = physical.agent[agentidx].loc
    old_board_idx = LinearIndices(physical.board_dim)[old_loc]
    new_board_idx = LinearIndices(physical.board_dim)[destination]
    
    physical.board[old_board_idx].occupant = 0
    physical.agent[agentidx].loc = destination
    physical.board[new_board_idx].occupant = agentidx
end


function move_in_direction(physical, agentidx, direction)
    newloc = physical.agent[agentidx].loc + DirectionDelta[direction]
    move_agent(physical, agentidx, newloc)
end


#######
"""
This type will be used by a macro called `@react` to generate events.
```
@react tomove(physical) begin
    @match changed(physical.board[loc].occupant)
    @generate direction ∈ keys(DirectionDelta)
    @if begin
        agent = physical.board[loc].occupant
        agent > 0 &&
        physical.board[loc + direction] == 0 &&
        checkbounds(physical.board, loc + direction)
    end
    @action MoveTransition(agent, direction)
end
```
"""


####### transitions
abstract type BoardTransition <: SimTransition end

"""
A dynamic generator of events. This looks at a changed place in the 
physical state and generates clock keys for events that could
depend on that place.
"""
function tomove_generate_event(physical, place_key, existing_events)
    # In this function, a variabled name that starts with `sym_` will be
    # generated by a macro, so it will be replaced with a unique name.

    # Select based on the place key.
    sym_array_name, sym_index_value, sym_struct_value... = place_key
    if sym_array_name != :board || sym_struct_value != (:occupant,)
        return nothing
    end
    # loc comes from matching the place key.
    loc_linear = sym_index_value
    loc_cartesian = physical.board_dim[loc_linear]

    # Not sure where to define this type BoardTransition.
    sym_create = BoardTransition[]
    sym_depends = Set{PlaceKey}[]
    sym_enabled = Function[]

    # Create the set of generative elements. We will do a for-loop over
    # these, but we need to insert code into the for-loop.
    # The top of the for-loop comes from the @generate macro.
    for direction in keys(DirectionDelta)
        # Inserted code at beginning.
        resetread(physical)

        # Now comes the code block from @if.
        sym_should_enable = begin
            agent = physical.board[loc_linear].occupant
            new_loc = loc_cartesian + DirectionDelta[direction]
            if checkbounds(Bool, physical.board_dim, new_loc)
                new_loc_linear = LinearIndices(physical.board_dim)[new_loc]
                agent > 0 &&
                  physical.board[new_loc_linear].occupant == 0
            else
                false
            end
        end

        # Inserted code at ending.
        if sym_should_enable
            input_places = wasread(physical)
            
            # This constructor call comes from the @action macro.
            transition = MoveTransition(agent, direction)

            # Then back to the inserted code.
            clock_key(transition) in existing_events && continue
            # The point of this is to make a new transition.
            push!(sym_create, transition)
            # That transition depends on the input places just read during @if.
            push!(sym_depends, input_places)
            # And we need to be able to disable the transition if
            # the @if condition is no longer true, so save that function.
            # Capture the current values in the closure
            let loc_linear_capture = loc_linear, direction_capture = direction
                push!(sym_enabled, function(physical)
                    # This will capture place and the generated variables.
                    loc_cartesian_capture = physical.board_dim[loc_linear_capture]
                    sym_should_enable = begin
                        agent = physical.board[loc_linear_capture].occupant
                        new_loc = loc_cartesian_capture + DirectionDelta[direction_capture]
                        if checkbounds(Bool, physical.board_dim, new_loc)
                            new_loc_linear = LinearIndices(physical.board_dim)[new_loc]
                            agent > 0 &&
                                physical.board[new_loc_linear].occupant == 0
                        else
                            false
                        end
                    end
                    return sym_should_enable
                end)
            end
        end
    end
    if isempty(sym_create)
        return nothing
    else
        return (create=sym_create, depends=sym_depends, enabled=sym_enabled)
    end
end


struct MoveTransition <: BoardTransition
    who::Int
    direction::Direction
end


clock_key(mt::MoveTransition) = ClockKey((:MoveTransition, mt.who, mt.direction))


function enable(tn::MoveTransition, sampler, physical, when, rng)
    enable!(sampler, clock_key(tn), Weibull(1.0), when, when, rng)
    return nothing
end


# Firing also transitions enabled -> disabled.
function fire!(tn::MoveTransition, physical)
    move_in_direction(physical, tn.who, tn.direction)
    return nothing
end



function initialize!(physical::PhysicalState, individuals::Int, rng)
    for ind_idx in 1:individuals
        loc = rand(rng, physical.board_dim)
        board_idx = LinearIndices(physical.board_dim)[loc]
        while physical.board[board_idx].occupant != 0
            loc = rand(rng, physical.board_dim)
            board_idx = LinearIndices(physical.board_dim)[loc]
        end
        move_agent(physical, ind_idx, loc)
    end
end



function run(event_count)
    Sampler = CombinedNextReaction{ClockKey,Float64}
    agent_cnt = 9
    raw_board = zeros(Int, 10, 10)
    for i in 1:agent_cnt
        raw_board[i] = i
    end
    physical = BoardState(raw_board)
    sim = SimulationFSM(
        physical,
        Sampler(),
        2947223
    )
    initialize!(sim.physical, agent_cnt, sim.rng)
    @assert isconsistent(sim.physical) "The initial physical state is inconsistent"
    deal_with_changes(sim)
    @assert isconsistent(sim)
    for i in 1:event_count
        (when, what) = next(sim.sampler, sim.when, sim.rng)
        if isfinite(when) && !isnothing(what)
            sim.when = when
            whatevent = sim.enabled_events[what]
            fire!(whatevent, sim.physical)
            remove_event!(sim, what)
            deal_with_changes(sim)
            @assert isconsistent(sim)
        end
    end
end
